// Generated by gencpp from file rosbot_ekf/Configuration.msg
// DO NOT EDIT!


#ifndef ROSBOT_EKF_MESSAGE_CONFIGURATION_H
#define ROSBOT_EKF_MESSAGE_CONFIGURATION_H

#include <ros/service_traits.h>


#include <rosbot_ekf/ConfigurationRequest.h>
#include <rosbot_ekf/ConfigurationResponse.h>


namespace rosbot_ekf
{

struct Configuration
{

typedef ConfigurationRequest Request;
typedef ConfigurationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Configuration
} // namespace rosbot_ekf


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rosbot_ekf::Configuration > {
  static const char* value()
  {
    return "b942000b3d255d27335aa543bc4443e3";
  }

  static const char* value(const ::rosbot_ekf::Configuration&) { return value(); }
};

template<>
struct DataType< ::rosbot_ekf::Configuration > {
  static const char* value()
  {
    return "rosbot_ekf/Configuration";
  }

  static const char* value(const ::rosbot_ekf::Configuration&) { return value(); }
};


// service_traits::MD5Sum< ::rosbot_ekf::ConfigurationRequest> should match 
// service_traits::MD5Sum< ::rosbot_ekf::Configuration > 
template<>
struct MD5Sum< ::rosbot_ekf::ConfigurationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rosbot_ekf::Configuration >::value();
  }
  static const char* value(const ::rosbot_ekf::ConfigurationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosbot_ekf::ConfigurationRequest> should match 
// service_traits::DataType< ::rosbot_ekf::Configuration > 
template<>
struct DataType< ::rosbot_ekf::ConfigurationRequest>
{
  static const char* value()
  {
    return DataType< ::rosbot_ekf::Configuration >::value();
  }
  static const char* value(const ::rosbot_ekf::ConfigurationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rosbot_ekf::ConfigurationResponse> should match 
// service_traits::MD5Sum< ::rosbot_ekf::Configuration > 
template<>
struct MD5Sum< ::rosbot_ekf::ConfigurationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rosbot_ekf::Configuration >::value();
  }
  static const char* value(const ::rosbot_ekf::ConfigurationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosbot_ekf::ConfigurationResponse> should match 
// service_traits::DataType< ::rosbot_ekf::Configuration > 
template<>
struct DataType< ::rosbot_ekf::ConfigurationResponse>
{
  static const char* value()
  {
    return DataType< ::rosbot_ekf::Configuration >::value();
  }
  static const char* value(const ::rosbot_ekf::ConfigurationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROSBOT_EKF_MESSAGE_CONFIGURATION_H
