(cl:in-package iiwa_msgs-msg)
(cl:export '(CARTESIAN_STIFFNESS-VAL
          CARTESIAN_STIFFNESS
          CARTESIAN_DAMPING-VAL
          CARTESIAN_DAMPING
          NULLSPACE_STIFFNESS-VAL
          NULLSPACE_STIFFNESS
          NULLSPACE_DAMPING-VAL
          NULLSPACE_DAMPING
))