; Auto-generated. Do not edit!


(cl:in-package iiwa_msgs-msg)


;//! \htmlinclude MoveToCartesianPoseFeedback.msg.html

(cl:defclass <MoveToCartesianPoseFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass MoveToCartesianPoseFeedback (<MoveToCartesianPoseFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <MoveToCartesianPoseFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'MoveToCartesianPoseFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name iiwa_msgs-msg:<MoveToCartesianPoseFeedback> is deprecated: use iiwa_msgs-msg:MoveToCartesianPoseFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <MoveToCartesianPoseFeedback>) ostream)
  "Serializes a message object of type '<MoveToCartesianPoseFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <MoveToCartesianPoseFeedback>) istream)
  "Deserializes a message object of type '<MoveToCartesianPoseFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<MoveToCartesianPoseFeedback>)))
  "Returns string type for a message object of type '<MoveToCartesianPoseFeedback>"
  "iiwa_msgs/MoveToCartesianPoseFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'MoveToCartesianPoseFeedback)))
  "Returns string type for a message object of type 'MoveToCartesianPoseFeedback"
  "iiwa_msgs/MoveToCartesianPoseFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<MoveToCartesianPoseFeedback>)))
  "Returns md5sum for a message object of type '<MoveToCartesianPoseFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'MoveToCartesianPoseFeedback)))
  "Returns md5sum for a message object of type 'MoveToCartesianPoseFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<MoveToCartesianPoseFeedback>)))
  "Returns full string definition for message of type '<MoveToCartesianPoseFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'MoveToCartesianPoseFeedback)))
  "Returns full string definition for message of type 'MoveToCartesianPoseFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <MoveToCartesianPoseFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <MoveToCartesianPoseFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'MoveToCartesianPoseFeedback
))
