; Auto-generated. Do not edit!


(cl:in-package iiwa_msgs-msg)


;//! \htmlinclude MoveToJointPositionFeedback.msg.html

(cl:defclass <MoveToJointPositionFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass MoveToJointPositionFeedback (<MoveToJointPositionFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <MoveToJointPositionFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'MoveToJointPositionFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name iiwa_msgs-msg:<MoveToJointPositionFeedback> is deprecated: use iiwa_msgs-msg:MoveToJointPositionFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <MoveToJointPositionFeedback>) ostream)
  "Serializes a message object of type '<MoveToJointPositionFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <MoveToJointPositionFeedback>) istream)
  "Deserializes a message object of type '<MoveToJointPositionFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<MoveToJointPositionFeedback>)))
  "Returns string type for a message object of type '<MoveToJointPositionFeedback>"
  "iiwa_msgs/MoveToJointPositionFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'MoveToJointPositionFeedback)))
  "Returns string type for a message object of type 'MoveToJointPositionFeedback"
  "iiwa_msgs/MoveToJointPositionFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<MoveToJointPositionFeedback>)))
  "Returns md5sum for a message object of type '<MoveToJointPositionFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'MoveToJointPositionFeedback)))
  "Returns md5sum for a message object of type 'MoveToJointPositionFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<MoveToJointPositionFeedback>)))
  "Returns full string definition for message of type '<MoveToJointPositionFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'MoveToJointPositionFeedback)))
  "Returns full string definition for message of type 'MoveToJointPositionFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <MoveToJointPositionFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <MoveToJointPositionFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'MoveToJointPositionFeedback
))
