// Generated by gencpp from file iiwa_msgs/ConfigureControlMode.msg
// DO NOT EDIT!


#ifndef IIWA_MSGS_MESSAGE_CONFIGURECONTROLMODE_H
#define IIWA_MSGS_MESSAGE_CONFIGURECONTROLMODE_H

#include <ros/service_traits.h>


#include <iiwa_msgs/ConfigureControlModeRequest.h>
#include <iiwa_msgs/ConfigureControlModeResponse.h>


namespace iiwa_msgs
{

struct ConfigureControlMode
{

typedef ConfigureControlModeRequest Request;
typedef ConfigureControlModeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ConfigureControlMode
} // namespace iiwa_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::iiwa_msgs::ConfigureControlMode > {
  static const char* value()
  {
    return "680a54772ae74cfe325dd171700c3d78";
  }

  static const char* value(const ::iiwa_msgs::ConfigureControlMode&) { return value(); }
};

template<>
struct DataType< ::iiwa_msgs::ConfigureControlMode > {
  static const char* value()
  {
    return "iiwa_msgs/ConfigureControlMode";
  }

  static const char* value(const ::iiwa_msgs::ConfigureControlMode&) { return value(); }
};


// service_traits::MD5Sum< ::iiwa_msgs::ConfigureControlModeRequest> should match 
// service_traits::MD5Sum< ::iiwa_msgs::ConfigureControlMode > 
template<>
struct MD5Sum< ::iiwa_msgs::ConfigureControlModeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::iiwa_msgs::ConfigureControlMode >::value();
  }
  static const char* value(const ::iiwa_msgs::ConfigureControlModeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::iiwa_msgs::ConfigureControlModeRequest> should match 
// service_traits::DataType< ::iiwa_msgs::ConfigureControlMode > 
template<>
struct DataType< ::iiwa_msgs::ConfigureControlModeRequest>
{
  static const char* value()
  {
    return DataType< ::iiwa_msgs::ConfigureControlMode >::value();
  }
  static const char* value(const ::iiwa_msgs::ConfigureControlModeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::iiwa_msgs::ConfigureControlModeResponse> should match 
// service_traits::MD5Sum< ::iiwa_msgs::ConfigureControlMode > 
template<>
struct MD5Sum< ::iiwa_msgs::ConfigureControlModeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::iiwa_msgs::ConfigureControlMode >::value();
  }
  static const char* value(const ::iiwa_msgs::ConfigureControlModeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::iiwa_msgs::ConfigureControlModeResponse> should match 
// service_traits::DataType< ::iiwa_msgs::ConfigureControlMode > 
template<>
struct DataType< ::iiwa_msgs::ConfigureControlModeResponse>
{
  static const char* value()
  {
    return DataType< ::iiwa_msgs::ConfigureControlMode >::value();
  }
  static const char* value(const ::iiwa_msgs::ConfigureControlModeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // IIWA_MSGS_MESSAGE_CONFIGURECONTROLMODE_H
