// Generated by gencpp from file iiwa_msgs/SetEndpointFrame.msg
// DO NOT EDIT!


#ifndef IIWA_MSGS_MESSAGE_SETENDPOINTFRAME_H
#define IIWA_MSGS_MESSAGE_SETENDPOINTFRAME_H

#include <ros/service_traits.h>


#include <iiwa_msgs/SetEndpointFrameRequest.h>
#include <iiwa_msgs/SetEndpointFrameResponse.h>


namespace iiwa_msgs
{

struct SetEndpointFrame
{

typedef SetEndpointFrameRequest Request;
typedef SetEndpointFrameResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetEndpointFrame
} // namespace iiwa_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::iiwa_msgs::SetEndpointFrame > {
  static const char* value()
  {
    return "422abb646a850d7c7d04073e2d2f950e";
  }

  static const char* value(const ::iiwa_msgs::SetEndpointFrame&) { return value(); }
};

template<>
struct DataType< ::iiwa_msgs::SetEndpointFrame > {
  static const char* value()
  {
    return "iiwa_msgs/SetEndpointFrame";
  }

  static const char* value(const ::iiwa_msgs::SetEndpointFrame&) { return value(); }
};


// service_traits::MD5Sum< ::iiwa_msgs::SetEndpointFrameRequest> should match 
// service_traits::MD5Sum< ::iiwa_msgs::SetEndpointFrame > 
template<>
struct MD5Sum< ::iiwa_msgs::SetEndpointFrameRequest>
{
  static const char* value()
  {
    return MD5Sum< ::iiwa_msgs::SetEndpointFrame >::value();
  }
  static const char* value(const ::iiwa_msgs::SetEndpointFrameRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::iiwa_msgs::SetEndpointFrameRequest> should match 
// service_traits::DataType< ::iiwa_msgs::SetEndpointFrame > 
template<>
struct DataType< ::iiwa_msgs::SetEndpointFrameRequest>
{
  static const char* value()
  {
    return DataType< ::iiwa_msgs::SetEndpointFrame >::value();
  }
  static const char* value(const ::iiwa_msgs::SetEndpointFrameRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::iiwa_msgs::SetEndpointFrameResponse> should match 
// service_traits::MD5Sum< ::iiwa_msgs::SetEndpointFrame > 
template<>
struct MD5Sum< ::iiwa_msgs::SetEndpointFrameResponse>
{
  static const char* value()
  {
    return MD5Sum< ::iiwa_msgs::SetEndpointFrame >::value();
  }
  static const char* value(const ::iiwa_msgs::SetEndpointFrameResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::iiwa_msgs::SetEndpointFrameResponse> should match 
// service_traits::DataType< ::iiwa_msgs::SetEndpointFrame > 
template<>
struct DataType< ::iiwa_msgs::SetEndpointFrameResponse>
{
  static const char* value()
  {
    return DataType< ::iiwa_msgs::SetEndpointFrame >::value();
  }
  static const char* value(const ::iiwa_msgs::SetEndpointFrameResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // IIWA_MSGS_MESSAGE_SETENDPOINTFRAME_H
