// Generated by gencpp from file iiwa_msgs/SetPTPCartesianSpeedLimits.msg
// DO NOT EDIT!


#ifndef IIWA_MSGS_MESSAGE_SETPTPCARTESIANSPEEDLIMITS_H
#define IIWA_MSGS_MESSAGE_SETPTPCARTESIANSPEEDLIMITS_H

#include <ros/service_traits.h>


#include <iiwa_msgs/SetPTPCartesianSpeedLimitsRequest.h>
#include <iiwa_msgs/SetPTPCartesianSpeedLimitsResponse.h>


namespace iiwa_msgs
{

struct SetPTPCartesianSpeedLimits
{

typedef SetPTPCartesianSpeedLimitsRequest Request;
typedef SetPTPCartesianSpeedLimitsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetPTPCartesianSpeedLimits
} // namespace iiwa_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::iiwa_msgs::SetPTPCartesianSpeedLimits > {
  static const char* value()
  {
    return "f4c42c9db5a373c4820a5b6872a3a795";
  }

  static const char* value(const ::iiwa_msgs::SetPTPCartesianSpeedLimits&) { return value(); }
};

template<>
struct DataType< ::iiwa_msgs::SetPTPCartesianSpeedLimits > {
  static const char* value()
  {
    return "iiwa_msgs/SetPTPCartesianSpeedLimits";
  }

  static const char* value(const ::iiwa_msgs::SetPTPCartesianSpeedLimits&) { return value(); }
};


// service_traits::MD5Sum< ::iiwa_msgs::SetPTPCartesianSpeedLimitsRequest> should match 
// service_traits::MD5Sum< ::iiwa_msgs::SetPTPCartesianSpeedLimits > 
template<>
struct MD5Sum< ::iiwa_msgs::SetPTPCartesianSpeedLimitsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::iiwa_msgs::SetPTPCartesianSpeedLimits >::value();
  }
  static const char* value(const ::iiwa_msgs::SetPTPCartesianSpeedLimitsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::iiwa_msgs::SetPTPCartesianSpeedLimitsRequest> should match 
// service_traits::DataType< ::iiwa_msgs::SetPTPCartesianSpeedLimits > 
template<>
struct DataType< ::iiwa_msgs::SetPTPCartesianSpeedLimitsRequest>
{
  static const char* value()
  {
    return DataType< ::iiwa_msgs::SetPTPCartesianSpeedLimits >::value();
  }
  static const char* value(const ::iiwa_msgs::SetPTPCartesianSpeedLimitsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::iiwa_msgs::SetPTPCartesianSpeedLimitsResponse> should match 
// service_traits::MD5Sum< ::iiwa_msgs::SetPTPCartesianSpeedLimits > 
template<>
struct MD5Sum< ::iiwa_msgs::SetPTPCartesianSpeedLimitsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::iiwa_msgs::SetPTPCartesianSpeedLimits >::value();
  }
  static const char* value(const ::iiwa_msgs::SetPTPCartesianSpeedLimitsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::iiwa_msgs::SetPTPCartesianSpeedLimitsResponse> should match 
// service_traits::DataType< ::iiwa_msgs::SetPTPCartesianSpeedLimits > 
template<>
struct DataType< ::iiwa_msgs::SetPTPCartesianSpeedLimitsResponse>
{
  static const char* value()
  {
    return DataType< ::iiwa_msgs::SetPTPCartesianSpeedLimits >::value();
  }
  static const char* value(const ::iiwa_msgs::SetPTPCartesianSpeedLimitsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // IIWA_MSGS_MESSAGE_SETPTPCARTESIANSPEEDLIMITS_H
