// Generated by gencpp from file iiwa_msgs/SetSpeedOverride.msg
// DO NOT EDIT!


#ifndef IIWA_MSGS_MESSAGE_SETSPEEDOVERRIDE_H
#define IIWA_MSGS_MESSAGE_SETSPEEDOVERRIDE_H

#include <ros/service_traits.h>


#include <iiwa_msgs/SetSpeedOverrideRequest.h>
#include <iiwa_msgs/SetSpeedOverrideResponse.h>


namespace iiwa_msgs
{

struct SetSpeedOverride
{

typedef SetSpeedOverrideRequest Request;
typedef SetSpeedOverrideResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetSpeedOverride
} // namespace iiwa_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::iiwa_msgs::SetSpeedOverride > {
  static const char* value()
  {
    return "5cb6d9d155adc8ed76143d144d178f68";
  }

  static const char* value(const ::iiwa_msgs::SetSpeedOverride&) { return value(); }
};

template<>
struct DataType< ::iiwa_msgs::SetSpeedOverride > {
  static const char* value()
  {
    return "iiwa_msgs/SetSpeedOverride";
  }

  static const char* value(const ::iiwa_msgs::SetSpeedOverride&) { return value(); }
};


// service_traits::MD5Sum< ::iiwa_msgs::SetSpeedOverrideRequest> should match 
// service_traits::MD5Sum< ::iiwa_msgs::SetSpeedOverride > 
template<>
struct MD5Sum< ::iiwa_msgs::SetSpeedOverrideRequest>
{
  static const char* value()
  {
    return MD5Sum< ::iiwa_msgs::SetSpeedOverride >::value();
  }
  static const char* value(const ::iiwa_msgs::SetSpeedOverrideRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::iiwa_msgs::SetSpeedOverrideRequest> should match 
// service_traits::DataType< ::iiwa_msgs::SetSpeedOverride > 
template<>
struct DataType< ::iiwa_msgs::SetSpeedOverrideRequest>
{
  static const char* value()
  {
    return DataType< ::iiwa_msgs::SetSpeedOverride >::value();
  }
  static const char* value(const ::iiwa_msgs::SetSpeedOverrideRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::iiwa_msgs::SetSpeedOverrideResponse> should match 
// service_traits::MD5Sum< ::iiwa_msgs::SetSpeedOverride > 
template<>
struct MD5Sum< ::iiwa_msgs::SetSpeedOverrideResponse>
{
  static const char* value()
  {
    return MD5Sum< ::iiwa_msgs::SetSpeedOverride >::value();
  }
  static const char* value(const ::iiwa_msgs::SetSpeedOverrideResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::iiwa_msgs::SetSpeedOverrideResponse> should match 
// service_traits::DataType< ::iiwa_msgs::SetSpeedOverride > 
template<>
struct DataType< ::iiwa_msgs::SetSpeedOverrideResponse>
{
  static const char* value()
  {
    return DataType< ::iiwa_msgs::SetSpeedOverride >::value();
  }
  static const char* value(const ::iiwa_msgs::SetSpeedOverrideResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // IIWA_MSGS_MESSAGE_SETSPEEDOVERRIDE_H
