// Generated by gencpp from file iiwa_msgs/TimeToDestination.msg
// DO NOT EDIT!


#ifndef IIWA_MSGS_MESSAGE_TIMETODESTINATION_H
#define IIWA_MSGS_MESSAGE_TIMETODESTINATION_H

#include <ros/service_traits.h>


#include <iiwa_msgs/TimeToDestinationRequest.h>
#include <iiwa_msgs/TimeToDestinationResponse.h>


namespace iiwa_msgs
{

struct TimeToDestination
{

typedef TimeToDestinationRequest Request;
typedef TimeToDestinationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TimeToDestination
} // namespace iiwa_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::iiwa_msgs::TimeToDestination > {
  static const char* value()
  {
    return "b71b59cce98847d0bd0310eb052e8f3f";
  }

  static const char* value(const ::iiwa_msgs::TimeToDestination&) { return value(); }
};

template<>
struct DataType< ::iiwa_msgs::TimeToDestination > {
  static const char* value()
  {
    return "iiwa_msgs/TimeToDestination";
  }

  static const char* value(const ::iiwa_msgs::TimeToDestination&) { return value(); }
};


// service_traits::MD5Sum< ::iiwa_msgs::TimeToDestinationRequest> should match 
// service_traits::MD5Sum< ::iiwa_msgs::TimeToDestination > 
template<>
struct MD5Sum< ::iiwa_msgs::TimeToDestinationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::iiwa_msgs::TimeToDestination >::value();
  }
  static const char* value(const ::iiwa_msgs::TimeToDestinationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::iiwa_msgs::TimeToDestinationRequest> should match 
// service_traits::DataType< ::iiwa_msgs::TimeToDestination > 
template<>
struct DataType< ::iiwa_msgs::TimeToDestinationRequest>
{
  static const char* value()
  {
    return DataType< ::iiwa_msgs::TimeToDestination >::value();
  }
  static const char* value(const ::iiwa_msgs::TimeToDestinationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::iiwa_msgs::TimeToDestinationResponse> should match 
// service_traits::MD5Sum< ::iiwa_msgs::TimeToDestination > 
template<>
struct MD5Sum< ::iiwa_msgs::TimeToDestinationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::iiwa_msgs::TimeToDestination >::value();
  }
  static const char* value(const ::iiwa_msgs::TimeToDestinationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::iiwa_msgs::TimeToDestinationResponse> should match 
// service_traits::DataType< ::iiwa_msgs::TimeToDestination > 
template<>
struct DataType< ::iiwa_msgs::TimeToDestinationResponse>
{
  static const char* value()
  {
    return DataType< ::iiwa_msgs::TimeToDestination >::value();
  }
  static const char* value(const ::iiwa_msgs::TimeToDestinationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // IIWA_MSGS_MESSAGE_TIMETODESTINATION_H
