(cl:in-package iiwa_msgs-srv)
(cl:export '(MAXCARTESIANVELOCITY-VAL
          MAXCARTESIANVELOCITY
          MAXORIENTATIONVELOCITY-VAL
          MAXORIENTATIONVELOCITY
          MAXCARTESIANACCELERATION-VAL
          MAXCARTESIANACCELERATION
          MAXORIENTATIONACCELERATION-VAL
          MAXORIENTATIONACCELERATION
          MAXCARTESIANJERK-VAL
          MAXCARTESIANJERK
          MAXORIENTATIONJERK-VAL
          MAXORIENTATIONJERK
          SUCCESS-VAL
          SUCCESS
          ERROR-VAL
          ERROR
))